spring.application.name=Bus-Ticket-Booking
server.port=8085
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

##host database configuration
#spring.datasource.url=jdbc:mysql://10.10.167.197:3306/busticketbooking
#spring.datasource.username= client1
#spring.datasource.password=pass1

#local database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/busticketbooking
spring.datasource.username= root
spring.datasource.password=Javed123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=BusTicketBookingSecretKeyForJWTAuthenticationAndAuthorizationPurpose123
jwt.expiration=3600000

